# -*- coding: utf-8 -*-
"""Market Price Intelligence System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FrXziASyslwtxcEqWclZ_FPwUnedRWec
"""

import requests

url = "https://dummyjson.com/products"

print("Menghubungi API DummyJSON...")
response = requests.get(url)

data_mentah = response.json()

print("Status Koneksi:", response.status_code, "(200 artinya Sukses!)")
print("Jumlah produk yang berhasil ditarik:", len(data_mentah['products']), "item")

import pandas as pd


daftar_produk = data_mentah['products']

df = pd.DataFrame(daftar_produk)

df_bersih = df[['id', 'title', 'price', 'rating']]

print("Bentuk Data Setelah Di-Transformasi (5 Data Pertama):")
display(df_bersih.head())

from sqlalchemy import create_engine

db_user = 'postgres.elzmmbtunyppwusrkrse'
db_password = 'huangziyan17'
db_host = 'aws-1-ap-southeast-1.pooler.supabase.com'
db_port = '6543'
db_name = 'postgres'

print("Membangun jembatan koneksi ke Supabase...")
string_koneksi = f"postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}"
engine = create_engine(string_koneksi)

print("Sedang mengirim 30 data produk...")
df_bersih.to_sql('market_prices', engine, if_exists='append', index=False)

print("🎉 Sukses! Semua data berhasil mendarat di lemari arsip awanmu!")
